<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [3]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.28801407 0.44565665 0.11080443 ... 0.81857128 0.54662489 0.2310772 ]
 [0.76913476 0.22603269 0.56122056 ... 0.01618177 0.34963908 0.22463053]
 [0.87960497 0.79582397 0.75475911 ... 0.47150658 0.26950188 0.58634259]
 ...
 [0.42617712 0.2212465  0.18306885 ... 0.02450834 0.1197974  0.13839996]
 [0.19378211 0.37796134 0.12693517 ... 0.41033078 0.56482755 0.91080554]
 [0.96258469 0.87213797 0.61149988 ... 0.25194495 0.14795771 0.90434616]]
[[0.84721043 0.13865445 0.9732052  ... 0.18540669 0.25313297 0.55134592]
 [0.02115188 0.10337599 0.23374781 ... 0.77906103 0.6380297  0.9298549 ]
 [0.6593886  0.36590709 0.81797741 ... 0.90206777 0.39795414 0.66656888]
 ...
 [0.64253854 0.27007489 0.06889859 ... 0.93938202 0.32933278 0.23070815]
 [0.38654243 0.35002931 0.05553852 ... 0.52091821 0.11562647 0.58669198]
 [0.58407306 0.89311356 0.77245348 ... 0.24346965 0.34663917 0.39638385]]


In [28]:
def mult(a, b):
    n = len(a)
    result = [[0 for y in range(n)] for x in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += a[i][k] * b[k][j]
    return result

In [24]:
def np_mult(a, b):
    print(np.dot(a, b))
    return np.dot(a, b)

In [29]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)
print(type(M1))

<class 'list'>
CPU times: user 719 ms, sys: 4.79 ms, total: 724 ms
Wall time: 731 ms


In [26]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)
print(type(M2))

[[24.78749289 25.47505314 25.28497304 ... 23.27784959 25.56737683
  26.83494032]
 [25.49766416 24.64014494 26.29243185 ... 22.45949475 23.53634841
  26.8141027 ]
 [24.51387075 23.90887862 25.28321854 ... 22.33224793 22.34754077
  25.99577114]
 ...
 [26.30725027 26.35492634 27.03719397 ... 25.10551399 24.21655865
  28.04581915]
 [25.28210366 27.17572813 26.47750033 ... 24.00776755 24.11640469
  28.11096185]
 [25.11861251 24.58434211 25.74953035 ... 24.36631164 25.40773799
  28.98938701]]
<class 'numpy.ndarray'>
CPU times: user 1.5 ms, sys: 3.1 ms, total: 4.59 ms
Wall time: 3.04 ms


In [30]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [31]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.3428789  0.9285958  0.01070494] [0.14103945 0.76652503 0.66368399]


In [32]:
def scalar_product(a, b):
    result = 0.
    for i in range(3):
        result += a[i] * b[i]
    return result

In [33]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [34]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 18 µs, sys: 2 µs, total: 20 µs
Wall time: 24.3 µs
CPU times: user 136 µs, sys: 13 µs, total: 149 µs
Wall time: 468 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [50]:
def np_diag_2k(a):
    diag = a.diagonal()
    result = diag[diag % 2 == 0]
    if result.size == 0:
        return 0
    return result.sum()

In [53]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 4, 7, 9, 6],
       [4, 3, 8, 1, 9],
       [6, 8, 5, 5, 2],
       [9, 1, 6, 8, 5],
       [3, 6, 7, 9, 4]])

In [54]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 84 µs, sys: 8 µs, total: 92 µs
Wall time: 95.6 µs


20

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​

In [69]:
def cumsum(A):
    result = np.zeros(A.shape)
    n, m = A.shape
    for i in range(m):
        for j in range(n):
            result[j, i] = A[j, 0:i + 1].sum()
    return result

In [72]:
# зададим некоторую последовательность и проверим ее на вашей функции.
A = sps.uniform.rvs(size=10**3)
a = np.random.randint(1, 10, size=(5, 5))
print(a)
cumsum(a)

[[7 3 3 5 1]
 [9 7 9 3 5]
 [3 1 4 5 2]
 [5 2 2 1 2]
 [4 6 8 1 4]]


array([[ 7., 10., 13., 18., 19.],
       [ 9., 16., 25., 28., 33.],
       [ 3.,  4.,  8., 13., 15.],
       [ 5.,  7.,  9., 10., 12.],
       [ 4., 10., 18., 19., 23.]])

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [15]:
def np_transformation(X, a=1):
    n, m = X.shape
    result = np.zeros((n, 2 * m))
    for i in range(n):
        array = np.zeros(m)
        array[1:m:2] = a
        array[0:m:2] = X[i, 0:m:2] ** 3
        result[i][0 : m] = X[i]
        result[i][m : 2 * m] = array[::-1]
    return result

In [16]:
X = np.array([[100, 200, 300, 400, 500]])
np_transformation(X, 1)

array([[1.00e+02, 2.00e+02, 3.00e+02, 4.00e+02, 5.00e+02, 1.25e+08,
        1.00e+00, 2.70e+07, 1.00e+00, 1.00e+06]])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [34]:
def np_encode(a):
    array = np.array([])
    repeat = np.array([])
    current_element = a[0]
    counter = 1
    for i in range(1, len(a)):
        if a[i] == current_element:
            counter += 1
        else:
            array = np.append(array, current_element)
            repeat = np.append(repeat, counter)
            current_element = a[i]
            counter = 1
    array = np.append(array, current_element)
    repeat = np.append(repeat, counter)
    return array, repeat

In [35]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

np_encode(X)

(array([1., 2., 3., 1., 5., 2., 3.]), array([1., 2., 2., 2., 2., 1., 2.]))